# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171201_0125'),
        ('users', '0010_auto_20171130_2020'),
    ]

    operations = [
    ]
