# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20171202_2112'),
        ('users', '0012_auto_20171202_1813'),
    ]

    operations = [
    ]
