# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20171203_0229'),
        ('users', '0011_merge_20171203_1706'),
    ]

    operations = [
    ]
