# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20171204_1939'),
        ('users', '0068_auto_20171204_2041'),
    ]

    operations = [
    ]
